version: "3.8"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
